---

- hosts: web
  become: yes

  tasks:
  -  name: Install nginx
     apt:
        name=nginx
        state=latest
     notify:
        nginx systemd

  -  name: Install apache
     apt:
        name=apache2
        state=latest
     notify:
        apache2 systemd

  handlers:
  - name: apache2 systemd
    systemd:
      name: apache2.service
      enabled: yes
      state: started
  - name: nginx systemd
    systemd:
      name: nginx.service
      enabled: yes
      state: started