---

- hosts: centos
  become: yes

  tasks:
  -  name: Install the repository
     yum:
        name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
     notify:

  -  name: Install PostgreSQL
     yum:
        name=postgresql12-server
        state=latest
     notify:
        postgresql-12 systemd

  handlers:
  - name: postgresql-12 systemd
    systemd:
      name: postgresql-12.service
      enabled: no
      state: started
