---

- hosts: all
  become: yes

  tasks:
  -  name: Install zabbix agent on CentOS
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        zabbix-agent systemd

  -  name: Install zabbix agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd

  - name: Install script
    template:
     src: /etc/ansible/common/file/zabbix_agentd.conf
     dest: /etc/zabbix/zabbix_agentd.conf

  handlers:
  - name: zabbix-agent systemd
    systemd:
      name: zabbix-agent.service
      enabled: yes
      state: started
